made rollarchroot separate script

diff --git a/rollarch b/rollarch
--- a/rollarch
+++ b/rollarch
@@ -42,9 +42,9 @@ usage() {
   echo "  - create partitions"
   echo "  - check 'custom' at 192.168.$AIP2"
   echo "  - pacstrap"
-  echo "  - create chroot script"
   echo "  - arch-chroot"
   echo
+  echo "Rankmirrors takes long, but if you accept that, uncomment the lines marked RANK"
   exit 0
 }
 
@@ -53,15 +53,10 @@ if [[ $1 = "--help" ]] || [[ $1 = "-h" ]]; then
   usage
 fi
 
-raise()
-{
-  echo "${1}" >&2
-}
-
 ping -c 1 -W 1 8.8.8.8 &>/dev/null
 if [ $? != 0 ]
 then
-  raise 'Fatal: Internet not available. Fix first.'
+  echo 'Fatal: Internet not available. Fix first.' >&2
   exit 1
 fi
 
@@ -77,26 +72,26 @@ for req in DSK USR PW HST ZONE
 do
   if [ "${!req}" = "" ]
   then
-    raise "Fatal: ${req} missing!"
+    echo "Fatal: ${req} missing!" >&2
     exit 1
   fi
 done
 
 if [ ! -e $DSK ]
 then
-  raise 'Fatal: DSK wrong'
+  echo 'Fatal: DSK wrong' >&2
   exit 1
 fi
 
 if [ "$USR" = "root" ] || [ "$(echo $USR | sed -e 's/[a-z]//g')" != "" ]
 then
-  raise 'Fatal: USR wrong'
+  echo 'Fatal: USR wrong' >&2
   exit 1
 fi
 
 if [ $(find /usr/share/zoneinfo -iname "*$ZONE" | wc -l) = 0 ]
 then
-  raise 'Fatal: ZONE wrong'
+  echo 'Fatal: ZONE wrong' >&2
   exit 1
 fi
 
@@ -106,7 +101,9 @@ then
 fi
 
 
-if [[ ! "$AIP2" =~ ^([0-9]+[.][0-9]+)$ ]] && [[ "$AIP2" != "" ]] && [[ "$AIP2" != "no" ]]
+if [[ "$AIP2" = "" ]]; then
+  AIP2="no"
+elif [[ ! "$AIP2" =~ ^([0-9]+[.][0-9]+)$ ]] && [[ "$AIP2" != "no" ]]
 then
   AIP2="yes"
 fi
@@ -115,7 +112,7 @@ if [ "$LA_NG" != "" ]
 then
   if [ "$LA_NG" = "en_US" ] || [[ ! "$LA_NG" =~ ^([a-z][a-z]_[A-Z][A-Z])$ ]]
   then
-    raise 'additional LA_NG wrong'
+    echo 'additional LA_NG wrong' >&2
     exit 1
   fi
 fi
@@ -183,7 +180,7 @@ for diskpart in $(ls ${DSK}*); do
   fi
 done
 if [ "$ROOT" = "" ]; then
-  raise 'unable to find ROOT the partition'
+  echo 'unable to find ROOT the partition' >&2
   exit 1
 fi
 if [ "$SWAP" != "off" ]; then
@@ -193,7 +190,7 @@ mkfs -t ext4 -F $ROOT &>/dev/null
 yes y | tune2fs -U $(cat /proc/sys/kernel/random/uuid) $ROOT &>/dev/null
 mount $ROOT /mnt
 if [ "$BOOT" = "" ]; then
-  raise 'unable to find BOOT the partition'
+  echo 'unable to find BOOT the partition' >&2
   exit 1
 fi
 if [ "$UEFI" = "off" ]; then
@@ -207,7 +204,7 @@ mount $BOOT /mnt/boot
 # check 'custom'
 mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.org
 ##RANK: pacman -Sy --noconfirm pacman-contrib &>/dev/null
-if [[ "$AIP2" != "" ]] && [[ "$AIP2" != "yes" ]]; then
+if [[ "$AIP2" != "no" ]] && [[ "$AIP2" != "yes" ]]; then
   aip2server="http://192.168.$AIP2:8080"
   echo "Server = $aip2server" > /etc/pacman.d/mirrorlist
   if [[ -n $(curl -s "$aip2server" | grep "custom\.db") ]]; then
@@ -221,13 +218,13 @@ EOF
   fi
 fi
 
-cat /etc/pacman.d/mirrorlist.org >> /etc/pacman.d/mirrorlist
 #RANK: # rankmirrors takes too long
 #RANK: echo "Ranking mirrors ... "
 #RANK: MIRRORLIST_URL="https://www.archlinux.org/mirrorlist/?country=all&protocol=http&protocol=https&ip_version=4"
 #RANK: curl -s "$MIRRORLIST_URL" | \
 #RANK:     sed -e 's/^#Server/Server/' -e '/^#/d' | \
 #RANK:     rankmirrors -n 8 --max-time 0.1 - >> /etc/pacman.d/mirrorlist
+cat /etc/pacman.d/mirrorlist.org >> /etc/pacman.d/mirrorlist
 pacman -Sy
 
 
@@ -246,26 +243,8 @@ Server = $aip2server
 EOF
 fi
 
-
-# create chroot script
-
-cat > /mnt/rollarchroot << EOF
-#!/usr/bin/env bash
-
-# Script after arch-chroot
-#
-# - setup_time: using \$ZONE
-# - setup_locale: using \$LA_NG
-# - setup_escape: Caps_Lock becomes Escape
-# - setup_network: with \$IP2 and \$HST, use netctl, but also create systemd file
-# - setup_boot: EFI boot if /sys/firmware/efi, else BIOS using grub
-# - setup_fstab: wiht \$DSK partitions
-# - setup_user: using \$USR and \$PW, the latter also for root
-#
-# After installation, *delete* this file or at least the line with \$PW
-
-## see https://github.com/rpuntaie/rollarch
-
+# arch-chroot
+arch-chroot /mnt bash -c "
 DSK=$DSK
 USR=$USR
 PW='$PW'
@@ -278,340 +257,14 @@ BOOT=$BOOT
 SWAP=$SWAP
 ROOT=$ROOT
 UEFI=$UEFI
-
-setup_arch_proxy() {
- ln -s /var/lib/pacman/sync/*.db /var/cache/pacman/pkg
- cd /usr/lib/systemd/system/
- cat darkhttpd.service | sed -e "s/Webserver/ArchProxy/g" -e "s,/srv/http.*$,/var/cache/pacman/pkg --no-server-id --port 8080,g" > ArchProxy.service
- systemctl enable ArchProxy
-}
-
-setup_time(){
-  for z in \$(find /usr/share/zoneinfo/ -iname "*\$ZONE"); do
-    if [[ ! \$z =~ ^.*/right/.*$ ]] && [[ ! \$z =~ ^.*/posix/.*$ ]]
-    then
-      rm -rf /etc/localtime
-      ln -s "\$z" /etc/localtime
-      break
-    fi
-  done
-  hwclock --systohc
-  cat > /etc/systemd/timesyncd.conf << END
-[Time]
-NTP=0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org
-FallbackNTP=0.pool.ntp.org 1.pool.ntp.org
-RootDistanceMaxSec=5
-PollIntervalMinSec=32
-PollIntervalMaxSec=2048
-END
-  timedatectl set-ntp true
-}
-export -f setup_time
-
-setup_locale(){
-  if [ "\$LA_NG" != "" ]
-  then
-    cat /etc/locale.gen | grep -E "#\${LA_NG}.* UTF-8" | sed -r "s/^#(.*)/\1/" > /etc/locale.tmp
-  fi
-  echo 'en_US.UTF-8 UTF-8' >> /etc/locale.tmp
-  mv /etc/locale.tmp /etc/locale.gen
-  locale-gen
-  locale > /etc/locale.conf
-}
-export -f setup_locale
-
-setup_escape(){
-  # change: keycode  58 = Escape
-  local KBD=$(find /usr/share/kbd/keymaps/ -iname "us.map.gz")
-  cd "\${KBD%/*}"
-  KBD=\${KBD##*/}
-  cp \$KBD rollarch\$KBD.map.gz
-  gunzip rollarch\$KBD.map.gz
-  sed -ie "s/keycode *58 *= *Caps_Lock/keycode 58 = Escape/g" rollarch\$KBD.map
-  gzip rollarch\$KBD.map
-  cd -
-  loadkeys rollarch\$KBD
-  cat > /etc/vconsole.conf << END
-KEYMAP=rollarch\$KBD
-FONT=lat9w-16
-FONT_MAP=8859-1_to_uni
-END
-}
-export -f setup_escape
-
-#for VirtualBox use bridged to make static netctl work
-setup_network(){
-  echo \$HST > /etc/hostname
-  cat > /etc/hosts << END
-127.0.0.1     localhost
-::1           localhost
-127.0.0.1     \$HST.localdomain  \$HST
-END
-  if [ "\$IP2" != "dhcp" ]; then
-    #IP2="1.100"
-    local IPE=\${IP2##*.} #100
-    local IPB=\${IP2%\$IPE} #1.
-    local NS=192.168.\${IPB}1
-    local CIDR="192.168.\$IP2/24"
-    ## #systemd-resolved instead of
-    ## echo "nameserver \$NS" > /etc/resolv.conf
-    sed -i -e "s/#DNS=.*$/DNS=\$NS/g" -e "s/#FallbackDNS/FallbackDNS/g" -e "s/#LLMNR/LLMNR/g" -e "s/#Multi/Multi/g" /etc/systemd/resolved.conf
-  fi
-  for NIC in \$(ip link show|grep " UP \| DOWN "|sed "s/^[^:]: \([^:]\+\).*/\1/g"); do
-    if [ \${NIC:0:1} = "e" ] && [ "\$had_e" = "" ]; then
-      local had_e="yes"
-      if [ "\$IP2" != "dhcp" ]; then
-        cat > /etc/netctl/se << END
-Description='static ethernet'
-Interface=\$NIC
-Connection=ethernet
-IP=static
-Address=('\$CIDR')
-Gateway=('\$NS')
-DNS=('\$NS')
-END
-        cat > /etc/systemd/system/network.service << END
-[Unit]
-Description=Network Connectivity
-Wants=network.target
-Before=network.target
-BindTo=sys-subsystem-net-devices-\$NIC.device
-After=sys-subsystem-net-devices-\$NIC.device
-
-[Service]
-Type=oneshot
-RemainAfterExit=yes
-ExecStart=/usr/bin/ip link set dev \$NIC up
-ExecStart=/usr/bin/ip addr add \$CIDR dev \$NIC
-ExecStart=/usr/bin/ip route add default via \$NS
-ExecStop=/usr/bin/ip addr flush dev \$NIC
-ExecStop=/usr/bin/ip link set dev \$NIC down
-
-[Install]
-WantedBy=multi-user.target
-END
-        cat > /etc/systemd/network/20-wired.network << END
-[Match]
-Name=\$NIC
-
-[Network]
-Address=\$CIDR
-Gateway=\$NS
-DNS=\$NS
-LLMNR=yes
-MulticastDNS=yes
-
-[Route]
-Metric=10
-END
-      else
-        cat > /etc/netctl/de << END
-Description='dhcp ethernet'
-Interface=\$NIC
-Connection=ethernet
-IP=dhcp
-END
-        cat > /etc/systemd/network/20-wired.network << END
-[Match]
-Name=\$NIC
-
-[Network]
-DHCP=ipv4
-LLMNR=yes
-MulticastDNS=yes
-
-[DHCP]
-RouteMetric=10
-END
-      fi
-    elif [ \${NIC:0:1} = "w" ] && [ "\$had_w" = "" ]; then
-      local had_w="yes"
-      if [ "\$IP2" != "dhcp" ]; then
-        cat > /etc/netctl/sw << END
-Description='static wireless'
-Interface=\$NIC
-Connection=wireless
-Security=wpa
-ESSID='TODO'
-Key='TODO'
-IP=static
-Address=('\$CIDR')
-Gateway=('\$NS')
-DNS=('\$NS')
-END
-        cat > /etc/systemd/network/25-wireless.network << END
-[Match]
-Name=\$NIC
-
-[Network]
-Address=\$CIDR
-Gateway=\$NS
-DNS=\$NS
-LLMNR=yes
-MulticastDNS=yes
-
-[Route]
-Metric=20
-END
-      else
-        cat > /etc/netctl/dw << END
-Description='dhcp wireless'
-Interface=\$NIC
-Connection=wireless
-Security=wpa
-IP=dhcp
-ESSID='TODO'
-Key='TODO'
-END
-        cat > /etc/systemd/network/25-wireless.network << END
-[Match]
-Name=\$NIC
-
-[Network]
-DHCP=ipv4
-LLMNR=yes
-MulticastDNS=yes
-
-[DHCP]
-RouteMetric=20
-END
-      fi
-    fi
-  done
-  ## #systemd-networkd instead of netctl, but config for the latter was made
-  ## if [[ "\$IP2" = "dhcp" ]]; then
-  ##   netctl enable d\${NIC:0:1} &>/dev/null
-  ##   #systemctl enable dhcpcd &>/dev/null
-  ## else
-  ##   netctl enable s\${NIC:0:1} &>/dev/null
-  ##   #systemctl enable network &>/dev/null
-  ## fi
-  systemctl enable systemd-networkd &>/dev/null
-  systemctl enable systemd-resolved &>/dev/null
-  #edit /etc/exports to nfs export folders
-  systemctl enable nfs-server.service &>/dev/null
-  ## samba
-  cat > /etc/samba/smb.conf << END
-[global]
-   usershare path = /var/lib/samba/usershares
-   usershare max shares = 100
-   usershare allow guests = yes
-   usershare owner only = yes
-
-END
-  curl -Ls https://raw.githubusercontent.com/samba-team/samba/master/examples/smb.conf.default|sed \
-    -e "s,log file = .*$,logging = systemd,g" -e "s,MYGROUP,WORKGROUP,g" -e "s/\[global\]//g" >> /etc/samba/smb.conf
-  mkdir -p /var/lib/samba/usershares
-  groupadd -r sambashare &>dev/null
-  chown root:sambashare /var/lib/samba/usershares
-  chmod 1770 /var/lib/samba/usershares
-  systemctl enable smb nmb &>/dev/null
-}
-export -f setup_network
-
-setup_boot(){
-  UCODE=''
-  UCODE_STRING=''
-  if [ "\$(cat /proc/cpuinfo | grep GenuineIntel)" != "" ]; then
-    UCODE='intel-ucode'
-  elif [ "\$(cat /proc/cpuinfo | grep AuthenticAMD)" != "" ]; then
-    UCODE='amd-ucode'
-  fi
-  if [ "\$UCODE" != "" ]; then
-    UCODE_STRING="initrd  /\${UCODE}.img
+curl -OLs https://raw.githubusercontent.com/rpuntaie/rollarch/master/rollarchroot
+chmod a+x ./rollarchroot
+source ./rollarchroot
+setup_all
 "
-    pacman -S --needed --noconfirm \$UCODE &>/dev/null
-  fi
-  if [ "\$UEFI" = "on" ]; then
-    pacman -S --needed --noconfirm efibootmgr efitools &>/dev/null
-    bootctl --path=/boot install
-    PARTUUID="\$(blkid -s PARTUUID -o value \$ROOT)"
-    APPEND="options root=PARTUUID=\${PARTUUID} rw quiet splash loglevel=0 console=tty2"
-    echo "title   \${HST}
-linux   /vmlinuz-linux
-\${UCODE_STRING}initrd  /initramfs-linux.img
-\${APPEND}" > /boot/loader/entries/arch.conf
-  else
-    mkinitcpio -p linux
-    grub-install --target=i386-pc --recheck \$DSK &>/dev/null
-    grub-mkconfig -o "/boot/grub/grub.cfg" &>/dev/null
-  fi
-  echo "cifs" > /etc/modules-load.d/cifs.conf
-}
-export -f setup_boot
 
-setup_fstab(){
-  genfstab -U -p / > /etc/fstab
-  blkid -g
-  for info in \$(blkid -o value "\$BOOT"); do
-    if [ "\$info" != "msdos" ]; then
-      sed -ie "s#\$BOOT#UUID=\$info#" /etc/fstab
-      break
-    fi
-  done
-  for info in \$(blkid -o value "\$ROOT"); do
-    if [ "\$info" != "msdos" ]; then
-      sed -ie "s#\$ROOT#UUID=\$info#" /etc/fstab
-      break
-    fi
-  done
-  if [ "\$SWAP" != "off" ]; then
-    swapon \$SWAP
-    for info in \$(blkid -o value "\$SWAP"); do
-      if [ "\$info" != "msdos" ]; then
-        sed -ie "s#\$SWAP#UUID=\$info#" /etc/fstab
-        break
-      fi
-    done
-  fi
-  cat /etc/fstab | sed -r 's/^(# )?(\/etc|efivarfs).*//' > /etc/fstab.tmp
-  mv /etc/fstab.tmp /etc/fstab
-}
-export -f setup_fstab
-
-setup_user(){
-  sed -i -e "s/^# *\(%wheel ALL=(ALL) ALL\)/\1/" /etc/sudoers
-  echo -e "\$PW
-\$PW" | passwd
-  useradd -m -g users -G wheel,storage,power,video,audio,lp,games,scanner -s /bin/bash \$USR &>/dev/null
-  echo -e "\$PW
-\$PW" | passwd \$USR
-  echo -e "\$PW
-\$PW" | smbpasswd -a \$USR
-  gpasswd sambashare -a \$USR
-}
-export -f setup_user
-
-if [[ "\${BASH_SOURCE[0]}" == "\${0}" ]]
-then
-  setup_time
-  setup_locale
-  setup_escape
-  setup_network
-  setup_boot
-  setup_fstab
-
-  if [[ -z "\$PW" ]]; then
-    PW=\$(dialog --stdout --passwordbox "Enter password for \$USR and root" 0 0) || exit 1
-  fi
-  if [[ -n "\$PW" ]]; then
-    setup_user
-  fi
-
-  if [[ \$AIP2 = "yes" ]]; then
-    setup_arch_proxy
-  fi
-  exit
-fi
-
-EOF
-
-chmod a+x /mnt/rollarchroot
-
-# arch-chroot
-arch-chroot /mnt /rollarchroot
-sed -i -e "s/PW=.*$/PW=/g" /mnt/rollarchroot
 ln -sf /run/systemd/stub-resolv.conf /mnt/etc/resolv.conf &>/dev/null
+
 umount $BOOT &>/dev/null
 umount $ROOT &>/dev/null
 echo "
