refactoring and additional tests

diff --git a/rollarch b/rollarch
--- a/rollarch
+++ b/rollarch
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 
-declare -r myname=${0##*/}
-declare -r myver='0.0.1'
+ROLLARCH_VERSION='0.0.1'
 
-usage() {
-  echo "${myname} v${myver}"
+function rollarch_usage() 
+{
+  echo "${0##*/} v${ROLLARCH_VERSION}"
   echo
   echo "This file is from:"
   echo "  https://raw.githubusercontent.com/rpuntaie/rollarch/master/rollarch"
@@ -41,237 +41,247 @@ usage() {
   echo "  DOTS: URL to a bash installation script for dot files"
   echo
   echo "Desription:"
-  echo "  - check parameters"
-  echo "  - create partitions"
+  echo "  - check parameters and access to internet"
+  echo "  - create and mount partitions"
   echo "  - check 'custom' at 192.168.$AIP2"
   echo "  - pacstrap"
-  echo "  - arch-chroot"
+  echo "  - arch-chroot using rollarchroot script"
   echo
   exit 0
 }
 
-
-if [[ $1 = "--help" ]] || [[ $1 = "-h" ]]; then
-  usage
-fi
-
-ping -c 1 -W 1 8.8.8.8 &>/dev/null
-if [ $? != 0 ]
-then
-  echo 'Fatal: Internet not available. Fix first.' >&2
-  exit 1
-fi
-
-if [ "$(which ntpdate 2> /dev/null)" != "" ]
-then
-  ntpdate pool.ntp.org &>/dev/null
-  timedatectl set-local-rtc 1 &>/dev/null
-fi
-
-# check parameters
-
-for req in DSK USR PW HST ZONE
-do
-  if [ "${!req}" = "" ]
-  then
-    echo "Fatal: ${req} missing!" >&2
+function rollarch_check_internet()
+{
+  ping -c 1 -W 1 8.8.8.8 &>/dev/null
+  if [[ $? != 0 ]]; then
+    echo 'Fatal: Internet not available. Fix first.' >&2
     exit 1
   fi
-done
 
-if [ ! -e $DSK ]
-then
-  echo 'Fatal: DSK wrong' >&2
-  exit 1
-fi
-
-if [ "$USR" = "root" ] || [ "$(echo $USR | sed -e 's/[a-z]//g')" != "" ]
-then
-  echo 'Fatal: USR wrong' >&2
-  exit 1
-fi
-
-if [ $(find /usr/share/zoneinfo -iname "*$ZONE" | wc -l) = 0 ]
-then
-  echo 'Fatal: ZONE wrong' >&2
-  exit 1
-fi
-
-if [[ ! "$IP2" =~ ^([0-9]+[.][0-9]+)$ ]]
-then
-  IP2="dhcp"
-fi
+  if [[ "$(which ntpdate 2> /dev/null)" != "" ]]; then
+    ntpdate pool.ntp.org &>/dev/null
+    timedatectl set-local-rtc 1 &>/dev/null
+  fi
+}
 
 
-if [[ "$AIP2" = "" ]]; then
-  AIP2="no"
-elif [[ ! "$AIP2" =~ ^([0-9]+[.][0-9]+)$ ]] && [[ "$AIP2" != "no" ]]
-then
-  AIP2="yes"
-fi
-
-if [ "$LA_NG" != "" ]
-then
-  for la_ng in $LA_NG
+function rollarch_check_defines()
+{
+  for req in DSK USR PW HST ZONE
   do
-    if [ "$la_ng" = "en_US" ] || [[ ! "$la_ng" =~ ^([a-z][a-z]_[A-Z][A-Z])$ ]]
-    then
-      echo 'additional LA_NG wrong' >&2
+    if [[ "${!req}" == "" ]]; then
+      echo "Fatal: ${req} missing!" >&2
       exit 1
     fi
   done
-fi
 
-if [ "$SWAP" != "on" ]
-then
-  SWAP="off"
-fi
+  if [[ ! -e $DSK ]]; then
+    echo 'Fatal: DSK wrong' >&2
+    exit 1
+  fi
 
-if [ "$KM" == "" ]; then
-  KM="US"
-fi
+  if [[ "$USR" == "root" ]] || [[ "$(echo $USR | sed -e 's/[a-z]//g')" != "" ]]; then
+    echo 'Fatal: USR wrong' >&2
+    exit 1
+  fi
 
-if [ -e /sys/firmware/efi ]; then
-  UEFI="on"
-else
-  UEFI="off"
-fi
+  if [[ $(find /usr/share/zoneinfo -iname "*$ZONE" | wc -l) == 0 ]]; then
+    echo 'Fatal: ZONE wrong' >&2
+    exit 1
+  fi
 
-# create partitions
+  if [[ ! "$IP2" =~ ^([0-9]+[.][0-9]+)$ ]]; then
+    IP2="dhcp"
+  fi
 
-umount ${DSK}* 2> /dev/null
-diskstart=2048s
-diskpart=
-dd if=/dev/zero of=$DSK bs=1 count=2048 &>/dev/null
-#dd if=/dev/zero of=$DSK bs=1 count=2048
-if [ "$UEFI" = "off" ]; then
-  parted --script $DSK mklabel msdos &>/dev/null
-else
-  parted --script $DSK mklabel gpt &>/dev/null
-fi
-parted --script --align optimal $DSK mkpart primary fat16 $diskstart 192MiB &>/dev/null
-parted $DSK set 1 boot on &>/dev/null
-diskstart=192MiB
-if [ "$UEFI" = "off" ]; then
-  GRUB="grub"
-fi
-if [ "$SWAP" = "off" ]; then
-  parted --script --align optimal $DSK mkpart primary ext4 $diskstart 100% &>/dev/null
-  swapsize=0
-else
-  swapsize=$(cat /proc/meminfo | grep MemTotal | sed "s/[^:]*: *\(.*\) kB/\1000/g")
-  ((swapsize=swapsize+2**30))
-  swapsize=$(numfmt --to=si $swapsize)
-  parted --script --align optimal $DSK mkpart primary linux-swap $diskstart $swapsize &>/dev/null
-  parted --script --align optimal $DSK mkpart primary ext4 $swapsize 100% &>/dev/null
-fi
-BOOT=
-ROOT=
-for diskpart in $(ls ${DSK}*); do
-  if [[ "$diskpart" =~ ^([a-z/]+([0-9]n)?[0-9]p|[a-z/]+)[0-9]$ ]]; then
-    if [ "$diskpart" != "$DSK" ]; then
-      if [ "$BOOT" = "" ]; then
-        BOOT=$diskpart
-        echo "  boot: $BOOT"
-      elif [ "$SWAP" = "off" ]; then
-        ROOT=$diskpart
-        echo "  root: $ROOT"
-      elif [ "$SWAP" != "off" ]; then
-        if  [ "$SWAP" = "on" ]; then
-          SWAP=$diskpart
-          echo "  swap: $SWAP"
-        else
+
+  if [[ "$AIP2" == "" ]]; then
+    AIP2="no"
+  elif [[ ! "$AIP2" =~ ^([0-9]+[.][0-9]+)$ ]] && [[ "$AIP2" != "no" ]]; then
+    AIP2="yes"
+  fi
+
+  if [[ "$LA_NG" != "" ]]; then
+    for la_ng in $LA_NG
+    do
+      if [[ "$la_ng" == "en_US" ]] || [[ ! "$la_ng" =~ ^([a-z][a-z]_[A-Z][A-Z])$ ]]; then
+        echo 'additional LA_NG wrong' >&2
+        exit 1
+      fi
+    done
+  fi
+
+  if [[ "$SWAP" != "on" ]]; then
+    SWAP="off"
+  fi
+
+  if [[ "$KM" == "" ]]; then
+    KM="US"
+  fi
+
+  if [[ -e /sys/firmware/efi ]]; then
+    UEFI="on"
+  else
+    UEFI="off"
+  fi
+
+  MNT_PNT=${MNT_PNT:-/mnt}
+  ROLLARCH_MIRRORLIST=${ROLLARCH_MIRRORLIST:-/etc/pacman.d/mirrorlist}
+  USRPKGS="$@"
+}
+
+function roll_find_partitions()
+{
+  BOOT=
+  ROOT=
+  for diskpart in $(ls ${DSK}*); do
+    if [[ "$diskpart" =~ ^([a-z/]+([0-9]n)?[0-9]p|[a-z/]+)[0-9]$ ]]; then
+      if [[ "$diskpart" != "$DSK" ]]; then
+        if [[ "$BOOT" == "" ]]; then
+          BOOT=$diskpart
+          echo "  boot: $BOOT"
+        elif [[ "$SWAP" == "off" ]]; then
           ROOT=$diskpart
           echo "  root: $ROOT"
+        elif [[ "$SWAP" != "off" ]]; then
+          if  [[ "$SWAP" == "on" ]]; then
+            SWAP=$diskpart
+            echo "  swap: $SWAP"
+          else
+            ROOT=$diskpart
+            echo "  root: $ROOT"
+          fi
         fi
       fi
     fi
+  done
+  if [[ "$ROOT" == "" ]]; then
+    echo 'unable to find ROOT the partition' >&2
+    return 0
   fi
-done
-if [ "$ROOT" = "" ]; then
-  echo 'unable to find ROOT the partition' >&2
-  exit 1
-fi
-if [ "$SWAP" != "off" ]; then
-  yes y | mkswap $SWAP
-fi
-mkfs -t ext4 -F $ROOT &>/dev/null
-yes y | tune2fs -U $(cat /proc/sys/kernel/random/uuid) $ROOT &>/dev/null
-mount $ROOT /mnt
-if [ "$BOOT" = "" ]; then
-  echo 'unable to find BOOT the partition' >&2
-  exit 1
-fi
-if [ "$UEFI" = "off" ]; then
-  mkfs -t ext2 -F $BOOT &>/dev/null
-else
-  mkfs -t vfat $BOOT &>/dev/null
-fi
-mkdir -p /mnt/boot
-mount $BOOT /mnt/boot
+  if [[ "$BOOT" == "" ]]; then
+    echo 'unable to find BOOT the partition' >&2
+    return 0
+  fi
+  return 1
+}
 
-# check 'custom'
-PACMAN_MIRROR_LIST=${PACMAN_MIRROR_LIST:-/etc/pacman.d/mirrorlist}
-mv $PACMAN_MIRROR_LIST /etc/pacman.d/mirrorlist.org
-if [[ "$AIP2" != "no" ]] && [[ "$AIP2" != "yes" ]]; then
-  aip2server="http://192.168.$AIP2:8080"
-  if [[ $(head -n1 /etc/pacman.d/mirrorlist.org) != "Server = $aip2server" ]]; then
-    echo "Server = $aip2server" > /etc/pacman.d/mirrorlist
+
+function roll_mkfs()
+{
+  if [[ "$SWAP" != "off" ]]; then
+    yes y | mkswap $SWAP
   fi
-  if [[ $(tail -n1 /etc/pacman.conf) != "Server = $aip2server" ]] &&
-     [[ -n $(curl -s "$aip2server" | grep "custom\.db") ]]; then
-    cat >> /etc/pacman.conf << EOF
-[custom]
-SigLevel = Optional TrustAll
-Server = $aip2server
-EOF
+  mkfs -t ext4 -F $ROOT &>/dev/null
+  yes y | tune2fs -U $(cat /proc/sys/kernel/random/uuid) $ROOT &>/dev/null
+  if [[ "$UEFI" == "off" ]]; then
+    mkfs -t ext2 -F $BOOT &>/dev/null
   else
-    aip2server=
+    mkfs -t vfat $BOOT &>/dev/null
   fi
-fi
+  mkdir -p $MNT_PNT/boot
+}
 
-cat /etc/pacman.d/mirrorlist.org >> $PACMAN_MIRROR_LIST
-pacman -Sy
 
-META=
-if [[ "$@" != "" ]]
-then
-  META="$@"
-  pacstrap /mnt $GRUB $@
-else
-  pacstrap /mnt $GRUB arch-install-scripts base base-devel devtools dialog wpa_supplicant ntp nfs-utils samba sudo git python vim zsh
-fi
+function roll_mount()
+{
+  mount $ROOT $MNT_PNT
+  mount $BOOT $MNT_PNT/boot
+}
 
-genfstab -t PARTUUID /mnt >> ${MNT_ETC_FSTAB:-/mnt/etc/fstab}
 
-if [[ "$aip2server" != "" ]]; then
-  cat >> ${MNT_ETC_PACMAN_CONF:-/mnt/etc/pacman.conf} << EOF
+function rollarch_partition()
+{
+  umount ${DSK}* 2> /dev/null
+  diskstart=2048s
+  diskpart=
+  dd if=/dev/zero of=$DSK bs=1 count=2048 &>/dev/null
+  #dd if=/dev/zero of=$DSK bs=1 count=2048
+  if [[ "$UEFI" == "off" ]]; then
+    parted --script $DSK mklabel msdos &>/dev/null
+  else
+    parted --script $DSK mklabel gpt &>/dev/null
+  fi
+  parted --script --align optimal $DSK mkpart primary fat16 $diskstart 192MiB &>/dev/null
+  parted $DSK set 1 boot on &>/dev/null
+  diskstart=192MiB
+  if [[ "$UEFI" == "off" ]]; then
+    GRUB="grub"
+  fi
+  if [[ "$SWAP" == "off" ]]; then
+    parted --script --align optimal $DSK mkpart primary ext4 $diskstart 100% &>/dev/null
+    swapsize=0
+  else
+    swapsize=$(cat /proc/meminfo | grep MemTotal | sed "s/[^:]*: *\(.*\) kB/\1000/g")
+    ((swapsize=swapsize+2**30))
+    swapsize=$(numfmt --to=si $swapsize)
+    parted --script --align optimal $DSK mkpart primary linux-swap $diskstart $swapsize &>/dev/null
+    parted --script --align optimal $DSK mkpart primary ext4 $swapsize 100% &>/dev/null
+  fi
+  roll_find_partitions
+  [[ $? ]] || exit 1
+  roll_mkfs
+  roll_mount
+}
+
+function rollarch_mirrorlist()
+{
+  mv $ROLLARCH_MIRRORLIST $ROLLARCH_MIRRORLIST.org
+  if [[ "$AIP2" != "no" ]] && [[ "$AIP2" != "yes" ]]; then
+    aip2server="http://192.168.$AIP2:8080"
+    if [[ $(head -n1 $ROLLARCH_MIRRORLIST.org) != "Server = $aip2server" ]]; then
+      echo "Server = $aip2server" > $ROLLARCH_MIRRORLIST
+    fi
+    if [[ $(tail -n1 /etc/pacman.conf) != "Server = $aip2server" ]] &&
+       [[ -n $(curl -s "$aip2server" | grep "custom\.db") ]]; then
+      cat >> /etc/pacman.conf << EOF
 [custom]
 SigLevel = Optional TrustAll
 Server = $aip2server
 EOF
-fi
-
-if [[ ! -e rollarchroot ]]; then
-  curl -OLs https://raw.githubusercontent.com/rpuntaie/rollarch/master/rollarchroot
-  chmod a+x ./rollarchroot
-fi
-mv ./rollarchroot /mnt/
-
-#produces a "not found" error in bash, but if is entered
-if [[ ! $(type check_mnt_bash) =~ .*function.* ]]; then
-  function check_mnt_bash()
-  {
-    if [[ ! -e /mnt/usr/bin/bash ]]; then
-      exit 1
+    else
+      aip2server=
     fi
-  }
-fi
+  fi
+  cat $ROLLARCH_MIRRORLIST.org >> $ROLLARCH_MIRRORLIST
+}
 
-check_mnt_bash
 
-# arch-chroot
-arch-chroot /mnt bash -c "
+function rollarch_packstrap()
+{
+  pacman -Sy
+
+  if [[ "$USRPKGS" != "" ]]; then
+    pacstrap $MNT_PNT "$GRUB $USRPKGS"
+  else
+    pacstrap $MNT_PNT $GRUB arch-install-scripts base base-devel devtools dialog wpa_supplicant ntp nfs-utils samba sudo git python vim zsh
+  fi
+
+  mkdir -p $MNT_PNT/etc
+  genfstab -t PARTUUID $MNT_PNT >> $MNT_PNT/etc/fstab
+  if [[ "$aip2server" != "" ]]; then
+    cat >> $MNT_PNT/etc/pacman.conf << EOF
+[custom]
+SigLevel = Optional TrustAll
+Server = $aip2server
+EOF
+  fi
+
+  if [[ ! -e rollarchroot ]]; then
+    curl -OLs https://raw.githubusercontent.com/rpuntaie/rollarch/master/rollarchroot
+    chmod a+x ./rollarchroot
+  fi
+  mv ./rollarchroot $MNT_PNT
+
+  if [[ ! -e $MNT_PNT/usr/bin/bash ]]; then
+    exit 1
+  fi
+}
+
+
+function rollarch_chroot()
+{
+  arch-chroot $MNT_PNT bash -c "
 DSK=$DSK
 USR=$USR
 PW='$PW'
@@ -284,13 +294,13 @@ BOOT=$BOOT
 SWAP=$SWAP
 ROOT=$ROOT
 UEFI=$UEFI
-META='$META'
+USRPKGS='$USRPKGS'
 KM='$KM'
 DOTS='$DOTS'
 . ./rollarchroot
 setup_all
-if [[ -n \$META ]]; then
-  for m in \$META; do
+if [[ -n \$USRPKGS ]]; then
+  for m in \$USRPKGS; do
     if [[ "\$m" =~ .*-meta ]]; then
       #make explicit
       pacman -D \$(LANG=C pacman -Si \$m |sed -n '/Depends\ On/,/:/p'|sed '\$d'|cut -d: -f2 |tr -d '>=[0-9]') --asexplicit
@@ -304,23 +314,57 @@ if [[ -n \$DOTS ]]; then
 fi
 "
 
-ln -sf /run/systemd/resolve/stub-resolv.conf /mnt/etc/resolv.conf &>/dev/null
+  ln -sf /run/systemd/resolve/stub-resolv.conf $MNT_PNT/etc/resolv.conf &>/dev/null
+}
 
-umount $BOOT &>/dev/null
-umount $ROOT &>/dev/null
-echo -e "\033[0;32m
-  Arch Linux is ready. '/rollarchroot' is still there.
 
-  'poweroff', remove media, boot
+function roll_umount()
+{
+  umount $BOOT &>/dev/null
+  umount $ROOT &>/dev/null
+}
 
-  cifs share and mount:
 
-  $ net usershare add cifs_share /home/$USR/path_to_cifs_share
-  $ mount -t cifs //196.168.$IP2/cifs_share cifs_share -o username=$USR,vers=2.0
+function rollarch_bye()
+{
+  roll_umount
+  echo -e "\033[0;32m
+Arch Linux is ready. '/rollarchroot' is still there.
 
-  nfs mount:
+'poweroff', remove media, boot
 
-  $ mount -t nfs 192.168.$IP2:/home/$USR/path_to_nfs_share nfs_share
+cifs share and mount:
+
+$ net usershare add cifs_share /home/$USR/path_to_cifs_share
+$ mount -t cifs //196.168.$IP2/cifs_share cifs_share -o username=$USR,vers=2.0
+
+nfs mount:
+
+$ mount -t nfs 192.168.$IP2:/home/$USR/path_to_nfs_share nfs_share
 
 "
+}
 
+
+function rollarch_main()
+{
+  if [[ $1 == "--help" ]] || [[ $1 == "-h" ]]; then
+    rollarch_usage
+  fi
+
+  rollarch_check_internet
+  rollarch_check_defines
+  rollarch_mirrorlist
+  rollarch_partition
+  rollarch_packstrap
+  rollarch_chroot
+  rollarch_bye
+}
+
+
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+    rollarch_main
+    if [[ $? -gt 0 ]]; then
+      exit 1
+    fi
+fi
diff --git a/rollarchroot b/rollarchroot
--- a/rollarchroot
+++ b/rollarchroot
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
-rollarchrootusage(){
+function rollarchrootusage(){
   echo "Required defines:"
-  echo "DSK USR PW HST LA_NG ZONE IP2 AIP2 BOOT SWAP ROOT UEFI"
+  echo "DSK USR PW HST LA_NG ZONE IP2 AIP2 BOOT SWAP ROOT UEFI KM"
   echo ""
   echo "Functions for after arch-chroot"
   echo ""
@@ -19,40 +19,39 @@ rollarchrootusage(){
   exit 0
 }
 
-if [[ $1 = "--help" ]] || [[ $1 = "-h" ]]; then
+if [[ $1 == "--help" ]] || [[ $1 == "-h" ]]; then
   rollarchrootusage
 fi
 
-if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
-    for req in DSK USR PW HST LA_NG ZONE IP2 AIP2 BOOT SWAP ROOT UEFI
-    do
-      if [ "${!req}" = "" ]
-      then
-        echo "Fatal: ${req} missing!" >&2
-        exit 1
-      fi
-    done
-fi
+for req in DSK USR PW HST LA_NG ZONE IP2 AIP2 BOOT SWAP ROOT UEFI KM
+do
+  if [[ "${!req}" == "" ]]; then
+    echo "Fatal: ${req} missing!" >&2
+    exit 1
+  fi
+done
 
-setup_arch_proxy() {
+function setup_arch_proxy() {
   pacman -S --needed --noconfirm darkhttpd &>/dev/null
-  ln -sf /var/lib/pacman/sync/*.db /var/cache/pacman/pkg
+  ln -s /var/lib/pacman/sync/*.db /var/cache/pacman/pkg
   cd /usr/lib/systemd/system/
   cat darkhttpd.service | sed -e "s/Webserver/ArchProxy/g" -e "s,/srv/http.*$,/var/cache/pacman/pkg --no-server-id --port 8080,g" > ArchProxy.service
   systemctl enable ArchProxy &>/dev/null
+  cd -
 }
 
-setup_time(){
+function setup_time(){
+  LOCALTIMECONF=${LOCALTIMECONF:-/etc/localtime}
+  SYSTEMTIMECONF=${SYSTEMTIMECONF:-/etc/systemd/timesyncd.conf}
   for z in $(find /usr/share/zoneinfo/ -iname "*$ZONE"); do
-    if [[ ! $z =~ ^.*/right/.*$ ]] && [[ ! $z =~ ^.*/posix/.*$ ]]
-    then
-      rm -rf /etc/localtime
-      ln -s "$z" /etc/localtime
+    if [[ ! $z =~ ^.*/right/.*$ ]] && [[ ! $z =~ ^.*/posix/.*$ ]]; then
+      rm -rf $LOCALTIMECONF
+      ln -s "$z" $LOCALTIMECONF
       break
     fi
   done
   hwclock --systohc
-  cat > /etc/systemd/timesyncd.conf <<EOF
+  cat > $SYSTEMTIMECONF <<EOF
 [Time]
 NTP=0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org
 FallbackNTP=0.pool.ntp.org 1.pool.ntp.org
@@ -63,24 +62,27 @@ EOF
   timedatectl set-ntp true
 }
 
-setup_locale(){
+function setup_locale(){
+  LOCALEGEN=${LOCALEGEN:-/etc/locale.gen}
+  LOCALECONF=${LOCALECONF:-/etc/locale.conf}
   local X=$LA_NG
   X+=" en_US"
   for x in $X
   do
-    sed -i -r "s/^#($x.* UTF-8)/\1/" /etc/locale.gen
+    sed -i -r "s/^#($x.* UTF-8)/\1/" $LOCALEGEN
   done
   locale-gen
-  LC_ALL="en_US.UTF-8" locale > /etc/locale.conf
+  LC_ALL="en_US.UTF-8" locale > $LOCALECONF
 }
 
-setup_escape(){
+function setup_escape(){
   local KBD=$(find /usr/share/kbd/keymaps/i386 -iname "$KM.map*")
   if [[ $(echo $KM | tr '[:upper:]' '[:lower:]') != $KM ]]; then
     # add: keycode  125 (WIN) = Caps_Lock 
     # change: keycode  58 (Caps_Lock) = Escape 
     cd "${KBD%/*}"
     KBD=${KBD##*/}
+    KBD=${KBD%%.*}
     cp $KBD rollarch$KBD.map.gz
     gunzip rollarch$KBD.map.gz
     sed -ie "s/keycode *58 *= *Caps_Lock/keycode 58 = Escape/g" rollarch$KBD.map
@@ -95,14 +97,23 @@ setup_escape(){
 }
 
 #for VirtualBox use bridged to have access to LAN
-setup_network(){
-  echo $HST > /etc/hostname
-  cat > /etc/hosts <<EOF
+function setup_network(){
+  LOADMODULECIFS=${LOADMODULECIFS:-/etc/modules-load.d/cifs.conf}
+  VARLIBSAMBAUSERSHARES=${VARLIBSAMBAUSERSHARES:-/var/lib/samba/usershares}
+  ETCSAMBASMB=${ETCSAMBASMB:-/etc/samba/smb.conf}
+  ETCSYSTEMDNETWORKWIRED=${ETCSYSTEMDNETWORKWIRED:-/etc/systemd/network/20-wired.network}
+  ETCSYSTEMDNETWORKWIRELESS=${ETCSYSTEMDNETWORKWIRELESS:-/etc/systemd/network/25-wireless.network}
+  ETCSYSTEMDSYSTEMNETWORKSERVICE=${ETCSYSTEMDSYSTEMNETWORKSERVICE:-/etc/systemd/system/network.service}
+  ETCSYSTEMDRESOLVEDCONF=${ETCSYSTEMDRESOLVEDCONF:-/etc/systemd/resolved.conf}
+  ETCHOSTS=${ETCHOSTS:-/etc/hosts}
+  ETCHOSTNAME=${ETCHOSTNAME:-/etc/hostname}
+  echo $HST > $ETCHOSTNAME
+  cat > $ETCHOSTS <<EOF
 127.0.0.1     localhost
 ::1           localhost
 127.0.0.1     $HST.localdomain  $HST
 EOF
-  if [ "$IP2" != "dhcp" ]; then
+  if [[ "$IP2" != "dhcp" ]]; then
     #IP2="1.100"
     local IPE=${IP2##*.} #100
     local IPB=${IP2%$IPE} #1.
@@ -110,13 +121,15 @@ EOF
     local CIDR="192.168.$IP2/24"
     ## #systemd-resolved instead of
     ## echo "nameserver $NS" > /etc/resolv.conf
-    sed -i -e "s/#DNS=.*$/DNS=$NS/g" -e "s/#FallbackDNS/FallbackDNS/g" -e "s/#LLMNR/LLMNR/g" -e "s/#Multi/Multi/g" /etc/systemd/resolved.conf
+    sed -i -e "s/#DNS=.*$/DNS=$NS/g" -e "s/#FallbackDNS/FallbackDNS/g" -e "s/#LLMNR/LLMNR/g" -e "s/#Multi/Multi/g" $ETCSYSTEMDRESOLVEDCONF
   fi
+  local had_e=""
+  local had_w=""
   for NIC in $(ip link show|grep " UP \| DOWN "|sed "s/^[^:]: \([^:]\+\).*/\1/g"); do
-    if [ ${NIC:0:1} = "e" ] && [ "$had_e" = "" ]; then
-      local had_e="yes"
-      if [ "$IP2" != "dhcp" ]; then
-        cat > /etc/systemd/system/network.service <<EOF
+    if [[ ${NIC:0:1} == "e" ]] && [[ "$had_e" == "" ]]; then
+      had_e="yes"
+      if [[ "$IP2" != "dhcp" ]]; then
+        cat > $ETCSYSTEMDSYSTEMNETWORKSERVICE <<EOF
 [Unit]
 Description=Network Connectivity
 Wants=network.target
@@ -136,7 +149,7 @@ ExecStop=/usr/bin/ip link set dev $NIC down
 [Install]
 WantedBy=multi-user.target
 EOF
-        cat > /etc/systemd/network/20-wired.network <<EOF
+        cat > $ETCSYSTEMDNETWORKWIRED <<EOF
 [Match]
 Name=$NIC
 
@@ -151,7 +164,7 @@ MulticastDNS=yes
 Metric=10
 EOF
       else
-        cat > /etc/systemd/network/20-wired.network <<EOF
+        cat > $ETCSYSTEMDNETWORKWIRED <<EOF
 [Match]
 Name=$NIC
 
@@ -164,10 +177,10 @@ MulticastDNS=yes
 RouteMetric=10
 EOF
       fi
-    elif [ ${NIC:0:1} = "w" ] && [ "$had_w" = "" ]; then
-      local had_w="yes"
-      if [ "$IP2" != "dhcp" ]; then
-        cat > /etc/systemd/network/25-wireless.network <<EOF
+    elif [[ ${NIC:0:1} == "w" ]] && [[ "$had_w" == "" ]]; then
+      had_w="yes"
+      if [[ "$IP2" != "dhcp" ]]; then
+        cat > $ETCSYSTEMDNETWORKWIRELESS <<EOF
 [Match]
 Name=$NIC
 
@@ -182,7 +195,7 @@ MulticastDNS=yes
 Metric=20
 EOF
       else
-        cat > /etc/systemd/network/25-wireless.network <<EOF
+        cat > $ETCSYSTEMDNETWORKWIRELESS <<EOF
 [Match]
 Name=$NIC
 
@@ -202,7 +215,7 @@ EOF
   #edit /etc/exports to nfs export folders
   systemctl enable nfs-server.service &>/dev/null
   ## samba
-  cat > /etc/samba/smb.conf <<EOF
+  cat > $ETCSAMBASMB <<EOF
 [global]
    usershare path = /var/lib/samba/usershares
    usershare max shares = 100
@@ -211,29 +224,31 @@ EOF
 
 EOF
   curl -Ls https://raw.githubusercontent.com/samba-team/samba/master/examples/smb.conf.default|sed \
-    -e "s,log file = .*$,logging = systemd,g" -e "s,MYGROUP,WORKGROUP,g" -e "s/\[global\]//g" >> /etc/samba/smb.conf
-  mkdir -p /var/lib/samba/usershares
-  groupadd -r sambashare &>dev/null
-  chown root:sambashare /var/lib/samba/usershares
-  chmod 1770 /var/lib/samba/usershares
+    -e "s,log file = .*$,logging = systemd,g" -e "s,MYGROUP,WORKGROUP,g" -e "s/\[global\]//g" >> $ETCSAMBASMB
+  mkdir -p $VARLIBSAMBAUSERSHARES
+  groupadd -r sambashare &>/dev/null
+  chown root:sambashare $VARLIBSAMBAUSERSHARES
+  chmod 1770 $VARLIBSAMBAUSERSHARES
   systemctl enable smb nmb &>/dev/null
   systemctl enable sshd &>/dev/null
+  echo "cifs" > $LOADMODULECIFS
 }
 
-setup_boot(){
+function setup_boot(){
+  ARCHLOADERCONF=${ARCHLOADERCONF:-/boot/loader/entries/arch.conf}
   UCODE=''
   UCODE_STRING=''
-  if [ "$(cat /proc/cpuinfo | grep GenuineIntel)" != "" ]; then
+  if [[ "$(cat /proc/cpuinfo | grep GenuineIntel)" != "" ]]; then
     UCODE='intel-ucode'
-  elif [ "$(cat /proc/cpuinfo | grep AuthenticAMD)" != "" ]; then
+  elif [[ "$(cat /proc/cpuinfo | grep AuthenticAMD)" != "" ]]; then
     UCODE='amd-ucode'
   fi
-  if [ "$UCODE" != "" ]; then
+  if [[ "$UCODE" != "" ]]; then
     UCODE_STRING="initrd  /${UCODE}.img
 "
     pacman -S --needed --noconfirm $UCODE &>/dev/null
   fi
-  if [ "$UEFI" = "on" ]; then
+  if [[ "$UEFI" == "on" ]]; then
     pacman -S --needed --noconfirm efibootmgr efitools &>/dev/null
     bootctl --path=/boot install
     PARTUUID="$(blkid -s PARTUUID -o value $ROOT)"
@@ -241,18 +256,17 @@ setup_boot(){
     echo "title   ${HST}
 linux   /vmlinuz-linux
 ${UCODE_STRING}initrd  /initramfs-linux.img
-${APPEND}" > /boot/loader/entries/arch.conf
+${APPEND}" > $ARCHLOADERCONF
   else
     mkinitcpio -p linux
     grub-install --target=i386-pc --recheck $DSK &>/dev/null
     grub-mkconfig -o "/boot/grub/grub.cfg" &>/dev/null
   fi
-  echo "cifs" > /etc/modules-load.d/cifs.conf
 }
 
-setup_user(){
+function setup_user(){
   useradd -m -g users -G wheel,uucp,storage,power,video,audio,lp,games,scanner,plugdev,lock -s /usr/bin/bash $USR &>/dev/null
-  if [ -e /usr/bin/zsh ]; then
+  if [[ -e /usr/bin/zsh ]]; then
     chsh -s /usr/bin/zsh $USR
   fi
   echo -e "$PW
@@ -265,7 +279,7 @@ $PW" | smbpasswd -a $USR
   sed -i -e "s/^# *\(%wheel ALL=(ALL) ALL\)/\1/" /etc/sudoers
 }
 
-setup_all(){
+function setup_all(){
   setup_time
   setup_locale
   setup_escape
@@ -279,7 +293,7 @@ setup_all(){
     setup_user
   fi
 
-  if [[ $AIP2 = "yes" ]]; then
+  if [[ $AIP2 == "yes" ]]; then
     setup_arch_proxy
   fi
 
@@ -289,8 +303,7 @@ setup_all(){
   fi
 }
 
-if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
-then
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
   setup_all
   exit 0
 fi
